Add the ability to reach the goal at the desired angle.
ut-amrl/graph_navigation pull request #28
Opened 2021-09-30 14:46 UTC by kvsikand

Basically, just turn in place once you get to the goal location.

At the moment, turn in place appears to happen very slowly...

2021-09-30 18:23 UTC, joydeep-b requested changes

2021-09-30 18:23 UTC, joydeep-b commented on src/navigation/navigation.cc
> +  try {
We don't use exceptions in our code. If something is throwing exceptions in our code, we need to fix it. If this catches an exception from a third party source, please add a comment to explain what it is.

2021-09-30 18:23 UTC, joydeep-b commented on src/navigation/navigation.cc
> +    printf("Could not find valid carrot\n");
This should go to stderr, not stdout.
```
fprintf(stderr, "Could not....");
```

2021-10-05 18:50 UTC, kvsikand commented
This has been validated on the real robot and updated to address review comments

2021-10-05 18:59 UTC, joydeep-b approved these changes

2021-10-18 20:50 UTC, merged